CREATE DATABASE BDII_AVALIACAO_I
USE BDII_AVALIACAO_I

DROP TABLE IF EXISTS TB_OFERECE_PACOTE_CLIENTE
DROP TABLE IF EXISTS TB_PACOTE_SAIDA
DROP TABLE IF EXISTS TB_PACOTE
DROP TABLE IF EXISTS TB_INTERESSE_CLIENTE
DROP TABLE IF EXISTS TB_DESTINO
DROP TABLE IF EXISTS TB_CLIENTE


CREATE TABLE TB_DESTINO (
   COD_DESTINO		INT NOT NULL PRIMARY KEY,
   DESCRICAO		VARCHAR(100) NOT NULL,
   ESTADO			CHAR(2) NOT NULL
)

INSERT INTO TB_DESTINO (COD_DESTINO, DESCRICAO, ESTADO)
VALUES (1, 'BARRA DE SÃO MIGUEL', 'AL')

INSERT INTO TB_DESTINO (COD_DESTINO, DESCRICAO, ESTADO)
VALUES (2, 'PORTO DE GALINHAS','PE')

INSERT INTO TB_DESTINO (COD_DESTINO, DESCRICAO, ESTADO)
VALUES (3, 'PORTO SEGURO','BA')

INSERT INTO TB_DESTINO (COD_DESTINO, DESCRICAO, ESTADO)
VALUES (4, 'SALVADOR','BA')

CREATE TABLE TB_CLIENTE (
   COD_CLIENTE		INT NOT NULL PRIMARY KEY,
   NM_CLIENTE		VARCHAR(50) NOT NULL,
   CPF				VARCHAR(13) NOT NULL,
   TELEFONE_CELULAR VARCHAR(20) NOT NULL,
   EMAIL			VARCHAR(100) NOT NULL
)

INSERT INTO TB_CLIENTE
VALUES(1, 'JOAO', '1111111111111','8804-1771','joao@gmail.com')

INSERT INTO TB_CLIENTE
VALUES(2, 'CARLOS', '2222222222222','8804-1772','carlos@gmail.com')

INSERT INTO TB_CLIENTE
VALUES(3, 'ROBERTA', '4444444444444','8804-1773','roberta@gmail.com')

INSERT INTO TB_CLIENTE
VALUES(4, 'PATRICIA', '5555555555555','8804-1774','patricia@gmail.com')

CREATE TABLE TB_INTERESSE_CLIENTE (
   ID_INTERESSE_CLIENTE INT NOT NULL PRIMARY KEY IDENTITY(1,1),
   COD_DESTINO			INT NOT NULL REFERENCES TB_DESTINO,
   COD_CLIENTE			INT NOT NULL REFERENCES TB_CLIENTE,
   UNIQUE (COD_DESTINO, COD_CLIENTE)
)

INSERT INTO TB_INTERESSE_CLIENTE
VALUES(1,1)

INSERT INTO TB_INTERESSE_CLIENTE
VALUES(2,2)

INSERT INTO TB_INTERESSE_CLIENTE
VALUES(3,2)

CREATE TABLE TB_PACOTE (
    COD_PACOTE		INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    DESCRICAO		VARCHAR(200) NOT NULL,
    COD_DESTINO		INT NOT NULL REFERENCES TB_DESTINO,
    NR_DIAS		    INT NOT NULL CHECK (NR_DIAS > 1),
    DATA_INICIAL    DATETIME NOT NULL,
    DATA_FINAL      DATETIME NOT NULL,
	STATUS          VARCHAR(10) DEFAULT('VÁLIDO') CHECK(STATUS IN ('VÁLIDO','EXPIRADO'))
)     

CREATE TABLE TB_PACOTE_SAIDA (
    ID_PACOTE_SAIDA INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    COD_PACOTE		INT NOT NULL REFERENCES TB_PACOTE,
    DATA_SAIDA		DATETIME NOT NULL,
    UNIQUE (COD_PACOTE, DATA_SAIDA)
)    
    
CREATE TABLE TB_OFERECE_PACOTE_CLIENTE (
    ID_OFERECE	INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    COD_CLIENTE INT NOT NULL REFERENCES TB_CLIENTE,
    COD_PACOTE	INT NOT NULL REFERENCES TB_PACOTE,
    OFERECIDO	CHAR(3) DEFAULT('NAO') CHECK (OFERECIDO IN ('SIM','NAO')),
	UNIQUE (COD_CLIENTE, COD_PACOTE)
)

CREATE OR ALTER PROCEDURE sp_att_pacote_saida
AS
BEGIN
    DECLARE @cod_pacote INT
    DECLARE @data_inicial DATETIME
    DECLARE @data_final DATETIME
    DECLARE @num_dias INT
    DECLARE @data_saida DATETIME

    DECLARE c_pacote CURSOR FOR
    SELECT COD_PACOTE, DATA_INICIAL, DATA_FINAL, NR_DIAS
    FROM TB_PACOTE

    OPEN c_pacote

    FETCH NEXT FROM c_pacote INTO @cod_pacote, @data_inicial, @data_final, @num_dias

    WHILE @@FETCH_STATUS = 0
    BEGIN
        IF @data_inicial IS NOT NULL AND @data_final IS NOT NULL AND @num_dias IS NOT NULL
        BEGIN
            SET @data_saida = DATEADD(DAY, @num_dias + 2, @data_inicial)

            IF @data_saida <= @data_final
            BEGIN
                IF EXISTS (SELECT 1 FROM TB_PACOTE_SAIDA WHERE COD_PACOTE = @cod_pacote)
                BEGIN
                    UPDATE TB_PACOTE_SAIDA
                    SET DATA_SAIDA = @data_saida
                    WHERE COD_PACOTE = @cod_pacote
                END
                ELSE
                BEGIN
                    INSERT INTO TB_PACOTE_SAIDA (COD_PACOTE, DATA_SAIDA)
                    VALUES (@cod_pacote, @data_saida)
                END
            END
        END

        FETCH NEXT FROM c_pacote INTO @cod_pacote, @data_inicial, @data_final, @num_dias
    END

    CLOSE c_pacote
    DEALLOCATE c_pacote
END

CREATE OR ALTER PROCEDURE sp_registrar_ofertas
AS
BEGIN
    INSERT INTO TB_OFERECE_PACOTE_CLIENTE (COD_CLIENTE, COD_PACOTE)
    SELECT C.COD_CLIENTE, P.COD_PACOTE
    FROM TB_CLIENTE C
    JOIN TB_PACOTE P ON C.INTERESSE = P.DESTINO
    WHERE NOT EXISTS (
        SELECT 1
        FROM TB_OFERECE_PACOTE_CLIENTE OPC
        WHERE OPC.COD_CLIENTE = C.COD_CLIENTE AND OPC.COD_PACOTE = P.COD_PACOTE
    )

    INSERT INTO TB_OFERECE_PACOTE_CLIENTE (COD_CLIENTE, COD_PACOTE)
    SELECT C.COD_CLIENTE, P.COD_PACOTE
    FROM TB_CLIENTE C
    CROSS JOIN TB_PACOTE P
    WHERE NOT EXISTS (
        SELECT 1
        FROM TB_OFERECE_PACOTE_CLIENTE OPC
        WHERE OPC.COD_CLIENTE = C.COD_CLIENTE AND OPC.COD_PACOTE = P.COD_PACOTE
    )
END
