CREATE OR ALTER PROCEDURE CALCULA_IMPOSTO @SALARIO FLOAT, @VALOR FLOAT OUTPUT
AS
DECLARE @DEDUCAO FLOAT
BEGIN
	IF(@SALARIO < 1372.82)
		BEGIN
			PRINT 'Não Há Valor a Ser PAGO'
		END
	IF(@SALARIO > 1372.81 AND @SALARIO <2743.25)
		BEGIN
			SET @DEDUCAO = 205.92
			SET @VALOR = @SALARIO* 1.15 - @DEDUCAO
			PRINT @VALOR
		END
	IF (@VALOR > 2743.25)
		BEGIN
			SET @DEDUCAO = 548.82
			SET @VALOR = @SALARIO*1.275 - @DEDUCAO
			PRINT @VALOR
		END
END